### Criar paciente
POST http://localhost:3000/pacientes
Content-Type: application/json

{
    "nome": "João Teste",
    "telefone": "11999999999",
    "email": "joao@teste.com",
    "dataNascimento": "1990-01-01"
}

### Criar paciente com dados incompletos (deve retornar erro)
POST http://localhost:3000/pacientes
Content-Type: application/json

{
  "telefone": "11111111111"
}

### Listar pacientes
GET http://localhost:3000/pacientes

### Obter paciente por ID
GET http://localhost:3000/pacientes/jiRoyLxcysPoRm9XaKZW

### Atualizar paciente
PATCH http://localhost:3000/pacientes/jiRoyLxcysPoRm9XaKZW
Content-Type: application/json

{
  "telefone": "11888880000"
}

### Deletar paciente
DELETE http://localhost:3000/pacientes/jiRoyLxcysPoRm9XaKZW